print("=== COMPARACIÓN DE DEUDA ===")
print("\nMetalPro (empresa demo):")
print("• Ratio Deuda/PN: 0.51x (funciona correctamente)")
print("• Mantiene deuda durante los 5 años")
print("\nTu empresa (Excel cargado):")
print("• Ratio Deuda/PN años 3-5: 0.00x")
print("• La deuda se paga completamente en año 3")
print("\nDIFERENCIA CLAVE:")
print("MetalPro tiene mucha más deuda inicial y probablemente")
print("no genera suficiente caja para pagarla toda rápidamente.")
print("\nTu empresa parece tener menos deuda y más flujo de caja,")
print("permitiendo pagar toda la deuda en 2-3 años.")
print("\nEsto NO es un bug, es el resultado del modelo financiero")
print("basado en los datos específicos de cada empresa.")
